import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import "@lottiefiles/lottie-player";

import StyledComponentsRegistry from '@/styles/styled-components/registry'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <StyledComponentsRegistry>
        <audio controls autoPlay={true}>
          <source src="/hbd.mp3" type="audio/mpeg" />
        </audio>
        <body className={inter.className}>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
